# Generated by Django 3.0.8 on 2020-07-10 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('filepath', models.FileField(upload_to='agenda/%Y/')),
                ('name', models.TextField(default='', max_length=25)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='name', max_length=25, null=True)),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video')], max_length=6)),
                ('album', models.CharField(choices=[('Autre', 'Autre')], max_length=25)),
                ('filepath', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('predicator', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('audio', models.FileField(blank=True, default=None, null=True, upload_to='audio/%Y/')),
                ('type', models.CharField(max_length=25)),
                ('avatar', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('note', models.FileField(blank=True, default=None, null=True, upload_to='doc/%Y/')),
            ],
            options={
                'db_table': 'predication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
