# Generated by Django 3.0.8 on 2020-07-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appv_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
