# Generated by Django 3.0.8 on 2020-07-09 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('filepath', models.FileField(upload_to='')),
                ('name', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=25)),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video')], max_length=6)),
                ('album', models.CharField(max_length=25)),
                ('filepath', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='MeditationFluxRss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2048)),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('predicator', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('audio', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('Prédication', 'Prédication'), ('Témoignage', 'Témoignage'), ('Partage', 'Partage'), ('Autre', 'Autre')], max_length=25)),
                ('avatar', models.FileField(upload_to='')),
                ('note', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'predication',
            },
        ),
    ]
